swift_version = '4.2'
use_frameworks!

target 'JelloSwift_Example' do
  pod 'JelloSwift', :path => '../'
  pod 'LibTessSwift', '~> 0.6.0'

  target 'JelloSwift_Tests' do
    inherit! :complete
    
    
  end
end
