# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod update --project-directory=Example
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/JelloSwift.xcworkspace -scheme JelloSwift-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,id=2523EF7F-852D-4268-A9A3-C55A4428EAE0,OS=10.3' | xcpretty # 2523EF7F-852D-4268-A9A3-C55A4428EAE0 = iPhone 5
- set -o pipefail && xcodebuild test -workspace Example/JelloSwift.xcworkspace -scheme JelloSwift-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPad Air 2,OS=10.3.1' | xcpretty
- pod lib lint
